/*  El objetivo de la practica es la creacion de los procedimientos capaces de 
    recibir parametros.
*/

-- CREAR TABLA EMPLEADOS --
create table EMPLEADOS (
    NOMBRE varchar2(30),
    DOCUMENTO varchar2(30),
    APELLIDO varchar2(30),
    SUELDO number,
    FECHA_INGRESO date
);

-- INSERTAR VALUES EN TABLA EMPLEADOS --
INSERT INTO EMPLEADOS VALUES ('Juan','222222','Perez',300,'10-OCT-1980');
INSERT INTO EMPLEADOS VALUES ('Luis','223333','Lopez',300,'12-MAY-1998');
INSERT INTO EMPLEADOS VALUES ('Marta','224444','Perez',500,'25-AUG-1990');
INSERT INTO EMPLEADOS VALUES ('Susana','225555','Garcia',400,'05-MAY-2000');
INSERT INTO EMPLEADOS VALUES ('Jose Maria','226666','Morales',400,'10-OCT-2005');

-- CREACION DEL PROCEDEIEMINTOS PARA AUMENTO DE SALARIO --
CREATE OR REPLACE PROCEDURE AUMENTO_SUELDO(ANIO IN NUMBER, PORCENTAJE IN NUMBER) AS 
BEGIN 
    UPDATE EMPLEADOS SET SUELDO=SUELDO+(SUELDO*PORCENTAJE/100) 
    WHERE (EXTRACT(YEAR FROM CURRENT_DATE)-EXTRACT(YEAR FROM FECHA_INGRESO))>ANIO; 
END AUMENTO;

EXECUTE AUMENTO_SUELDO(10,20); -- Ejecutar el procediemientos con los parametros

-- INSERT CON UN PROCEDIMIENTO --
CREATE OR REPLACE PROCEDURE INGRESAR_EMPLEADOS(DOCU IN varchar2, NOM IN varchar2, APE IN varchar2) AS
BEGIN
    INSERT INTO EMPLEADOS VALUES(DOCU,NOM,APE,NULL,NULL);
END INGRESAR_EMPLEADOS; 

EXECUTE INGRESAR_EMPLEADOS('444444','Emiliano','Pinos');